server:
  port: 8060

spring:
  application:
    name: server-user
  jmx:
    enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/easyiot?serverTimezone=GMT%2B8&useUnicode=true&amp&characterEncoding=utf-8
    username: root
    password: root
    druid:
      initialSize: 10
      minIdle: 10
      maxActive: 200
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


#security:
#  oauth2:
#    client:
#      client-id: client
#      client-secret: secret
#      access-token-uri: http://localhost:8040/oauth/token
#      user-authorization-uri: http://localhost:8040/oauth/authorize
#    resource:
#      token-info-uri: http://localhost:8040/oauth/check_token

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mybatis-plus:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: true





