server:
  port: 8030

spring:
  jmx:
    enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/easyiot?serverTimezone=GMT%2B8&useUnicode=true&amp&characterEncoding=utf-8
    username: root
    password: root

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5

mybatis-plus:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl